# Generated by Django 5.0 on 2023-12-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riyaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
